grammar;

Barm<A, B> = { A B, B A }
DeepBar<A, B, C> = {
    A Barm<B, C>,
}
Bar: (i32, i32) = {
    <a:r"[0-9]"> <b:r"[0-9]"> => (a.parse::<i32>().unwrap(), b.parse::<i32>().unwrap())
}

pub Foo: String = {
    <(a, b):Barm<"a", "b">> => {
        a.to_string() + b
    },
    <(a, (b, c)):DeepBar<"A", "B", "C">> => {
        a.to_string() + b + c
    },
    <(mut a, b):Bar> => {
        a += b;
        format!("{}{}", a, b)
    }
};
