
use util::tok::Tok;
use lalrpop_util::ErrorRecovery;

grammar<'input, 'e>(errors: &'e mut Vec<ErrorRecovery<(), Tok<'input>, &'static str>>);

extern {
    enum Tok<'input> {
        "+" => Tok::Plus,
        "/" => Tok::Div,
        Num => Tok::Num(<i32>)
    }
}

SkipExtraTokens: () = {
    => (),
    <!> => errors.push(<>),
};

Expr: () = {
    Num => (),

    <lhs: Num> "+" <rhs: Num> => (),
};

pub Item: ()  = {
    Expr SkipExtraTokens "/" => (),
    <!> => errors.push(<>)
};
