use std::cell::RefCell;

use crate::util::tok::Tok;
use lalrpop_util::ErrorRecovery;

grammar<'e, 'input>(errors: &'e RefCell<Vec<ErrorRecovery<(), Tok<'input>, &'static str>>>);

extern {
    enum Tok<'input> {
        "-" => Tok::Minus,
        "+" => Tok::Plus,
        "(" => Tok::LParen,
        ")" => Tok::RParen,
        Num => Tok::Num(<i32>)
    }
}

pub Item: String = {
    "+" => '+'.to_string(),
    "-" "-" "-" => "-".to_string(),
    "-" "-" <err: !> => { errors.borrow_mut().push(err); "!".to_string() },
    "(" <i: Item> ")" => format!("({})", i),
    "(" <err: !> ")" => { errors.borrow_mut().push(err); "()".to_string() },
};
