use std::cell::RefCell;

use util::tok::Tok;
use lalrpop_util::ErrorRecovery;

grammar<'e>(errors: &'e RefCell<Vec<ErrorRecovery<(), Tok, ()>>>);

extern {
    enum Tok {
        "-" => Tok::Minus,
        "+" => Tok::Plus,
        "(" => Tok::LParen,
        ")" => Tok::RParen,
        Num => Tok::Num(<i32>)
    }
}

pub Item: String = {
    "+" => '+'.to_string(),
    "-" "-" "-" => "-".to_string(),
    "-" "-" <err: !> => { errors.borrow_mut().push(err); "!".to_string() },
    "(" <i: Item> ")" => { format!("({})", i) },
    "(" <err: !> ")" => { errors.borrow_mut().push(err); "()".to_string() },
};
