use util::tok::Tok;
use lalrpop_util::ErrorRecovery;

#[LALR]
grammar<'input, 'e>(errors: &'e mut Vec<ErrorRecovery<usize, Tok, ()>>);

extern {
    type Location = usize;
    enum Tok {
        "(" => Tok::LParen,
        ")" => Tok::RParen,
        "+" => Tok::Plus,
        "-" => Tok::Minus,
        "/" => Tok::Div,
        Num => Tok::Num(<i32>)
    }
}

SkipExtraTokens: () = {
    => (),
    <!> => errors.push(<>),
};

pub Expr: ()  = {
    Expr1 => (),
    "+" Expr1 => (),
    Expr "/" Expr1 => (),
    Expr "+" Expr1 => (),
    Expr "-" Expr1 => (),
    Paren,
    ! => {
        errors.push(<>);
    }
};

Expr1: ()  = {
    Num => (),
};

Paren: ()  = {
    "(" Expr ")" => (),
};
