grammar(scale: i32)["LALR(1)"];

use util::tok::Tok;

extern {
    enum Tok {
        "(" => Tok::LParen,
        ")" => Tok::RParen,
        "-" => Tok::Minus,
        "+" => Tok::Plus,
        "*" => Tok::Times,
        "/" => Tok::Div,
        Num => Tok::Num(<i32>)
    }
}

pub Expr = {
    <l:Expr> "-" <r:Factor> => l - r,
    <l:Expr> "+" <r:Factor> => l + r,
    Factor,
};

Factor = {
    <l:Factor> "*" <r:Term> => l * r,
    <l:Factor> "/" <r:Term> => l / r,
    Term,
};

Term: i32 = {
    <n:Num> => n * scale,
    "(" <Expr> ")",
};
