grammar {
    use util::tok::Tok;

    extern token {
        enum Tok {
            "(" => Tok::LParen(..),
            ")" => Tok::RParen(..),
            "-" => Tok::Minus(..),
            "+" => Tok::Plus(..),
            "*" => Tok::Times(..),
            "/" => Tok::Div(..),
            "Num" => Tok::Num(<i32>)
        }
    }

    pub Expr: i32 = {
        <l:Expr> "-" <r:Factor> => l - r;
        <l:Expr> "+" <r:Factor> => l + r;
        Factor;
    };

    Factor = {
        <l:Factor> "*" <r:Term> => l * r;
        <l:Factor> "/" <r:Term> => l / r;
        Term;
    };

    Term = {
        <n:"Num"> => n;
        "(" <Expr> ")";
    };
}
