// Port of the `loc` test to use an internal tokenizer.  Also tests
// indirectly the case where there is a type/lifetime parameter
// (`'input`) that is not used in any nonterminal return type.

grammar;

pub Items: Vec<(usize, usize)> = {
    <@L> <@R> => vec![(<>)],

    <mut v:Items> <e:Spanned<"+">> => { v.push(e); v },

    <v:Items> "-" => v
};

Spanned<T>: (usize, usize) = {
    <@L> T <@R> => (<>)
};
