// Port of the `loc` test to use an internal tokenizer.  Also tests
// indirectly the case where there is a type/lifetime parameter
// (`'input`) that is not used in any nonterminal return type.


use util::tok::Tok;

grammar;

pub Items: Vec<(usize, usize)> = {
    <@L> <@R> => vec![(<>)];

    <v:Items> <e:Spanned<"+">> => {
        let mut v = v;
        v.push(e);
        v
    };

    <v:Items> "-" => v;
};

Spanned<T>: (usize, usize) = {
    <@L> T <@R> => (<>);
};
