use util::tok::Tok;

grammar;

extern {
    type Location = usize;

    enum Tok {
        "-" => Tok::Minus(..),
        "+" => Tok::Plus(..)
    }
}

pub Items: Vec<(usize, usize)> = {
    <@L> <@R> => vec![(<>)];

    <v:Items> <e:Spanned<"+">> => {
        let mut v = v;
        v.push(e);
        v
    };

    <v:Items> "-" => v;
};

Spanned<T>: (usize, usize) = {
    <@L> T <@R> => (<>);
};
