grammar;

// NOTE: This grammar is ambiguous without the match section

match {
    r"(?i-u)select",
    r"(?i-u)insert" => "INSERT",
    r"(?i-u)update" => UPDATE
} else {
    _
}

Keyword: String = {
    r"(?i-u)select" => String::from("SELECT"),
    "INSERT" => String::from("INSERT"),
    UPDATE => String::from("UPDATE")
};

Table: String = {
    <r"(?i-u)[a-z]+"> => String::from(<>)
};

pub Query: String = {
    <Keyword> <Table> => format!("{<>} {<>}")
};
