#!/bin/bash

ROOT=$(dirname $(dirname $0))

set -e

cd $ROOT/doc
mdbook build
cp -rf calculator pascal whitespace book
echo "Book has been built into $PWD/book"
echo "To view, open $PWD/book/index.html"
